spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/authentication/**
          filters:
            - AuthenticationFilter
        - id: file-storage-service
          uri: ${FILE_STORAGE_URL}
          predicates:
            - Path=/file-storage/**
          filters:
            - AuthenticationFilter

gateway:
  app:
    jwtSecret: ${SECRET_KEY}
