server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/authentication/**
          filters:
            - AuthenticationFilter

gateway:
  app:
    jwtSecret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
